# Generated by Django 2.0.2 on 2018-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20180311_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='police',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='victim',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
