# Generated by Django 2.0.2 on 2018-03-13 12:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0005_auto_20180313_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='police',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='victim',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='lawyer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='police',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='victim',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='police',
            name='email',
        ),
        migrations.RemoveField(
            model_name='police',
            name='id',
        ),
        migrations.RemoveField(
            model_name='police',
            name='password',
        ),
        migrations.RemoveField(
            model_name='police',
            name='username',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='email',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='id',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='password',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='username',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='police',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victim',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
