# Generated by Django 2.0.2 on 2018-03-15 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_victimcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimcase',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='victimcase',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to=settings.AUTH_USER_MODEL),
        ),
    ]
