# Generated by Django 2.0.2 on 2018-03-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20180315_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victimcase',
            name='lawyer',
        ),
    ]
