# Generated by Django 2.0.3 on 2018-03-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_remove_victimcase_lawyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('victim_name', models.CharField(max_length=100)),
                ('lawyer_name', models.CharField(max_length=100)),
            ],
        ),
    ]
